// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// PullRequestCreatePost implements POST /pullRequest/create operation.
//
// Создать PR и автоматически назначить до 2 ревьюверов
// из команды автора.
//
// POST /pullRequest/create
func (UnimplementedHandler) PullRequestCreatePost(ctx context.Context, req *PullRequestCreatePostReq) (r PullRequestCreatePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PullRequestMergePost implements POST /pullRequest/merge operation.
//
// Пометить PR как MERGED (идемпотентная операция).
//
// POST /pullRequest/merge
func (UnimplementedHandler) PullRequestMergePost(ctx context.Context, req *PullRequestMergePostReq) (r PullRequestMergePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PullRequestReassignPost implements POST /pullRequest/reassign operation.
//
// Переназначить конкретного ревьювера на другого из
// его команды.
//
// POST /pullRequest/reassign
func (UnimplementedHandler) PullRequestReassignPost(ctx context.Context, req *PullRequestReassignPostReq) (r PullRequestReassignPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TeamAddPost implements POST /team/add operation.
//
// Создать команду с участниками (создаёт/обновляет
// пользователей).
//
// POST /team/add
func (UnimplementedHandler) TeamAddPost(ctx context.Context, req *Team) (r TeamAddPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TeamGetGet implements GET /team/get operation.
//
// Получить команду с участниками.
//
// GET /team/get
func (UnimplementedHandler) TeamGetGet(ctx context.Context, params TeamGetGetParams) (r TeamGetGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersGetReviewGet implements GET /users/getReview operation.
//
// Получить PR'ы, где пользователь назначен ревьювером.
//
// GET /users/getReview
func (UnimplementedHandler) UsersGetReviewGet(ctx context.Context, params UsersGetReviewGetParams) (r *UsersGetReviewGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersSetIsActivePost implements POST /users/setIsActive operation.
//
// Установить флаг активности пользователя.
//
// POST /users/setIsActive
func (UnimplementedHandler) UsersSetIsActivePost(ctx context.Context, req *UsersSetIsActivePostReq) (r UsersSetIsActivePostRes, _ error) {
	return r, ht.ErrNotImplemented
}
