// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Error ErrorResponseError `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() ErrorResponseError {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val ErrorResponseError) {
	s.Error = val
}

func (*ErrorResponse) pullRequestMergePostRes() {}
func (*ErrorResponse) teamAddPostRes()          {}
func (*ErrorResponse) teamGetGetRes()           {}
func (*ErrorResponse) usersSetIsActivePostRes() {}

type ErrorResponseError struct {
	Code    ErrorResponseErrorCode `json:"code"`
	Message string                 `json:"message"`
}

// GetCode returns the value of Code.
func (s *ErrorResponseError) GetCode() ErrorResponseErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ErrorResponseError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ErrorResponseError) SetCode(val ErrorResponseErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ErrorResponseError) SetMessage(val string) {
	s.Message = val
}

type ErrorResponseErrorCode string

const (
	ErrorResponseErrorCodeTEAMEXISTS  ErrorResponseErrorCode = "TEAM_EXISTS"
	ErrorResponseErrorCodePREXISTS    ErrorResponseErrorCode = "PR_EXISTS"
	ErrorResponseErrorCodePRMERGED    ErrorResponseErrorCode = "PR_MERGED"
	ErrorResponseErrorCodeNOTASSIGNED ErrorResponseErrorCode = "NOT_ASSIGNED"
	ErrorResponseErrorCodeNOCANDIDATE ErrorResponseErrorCode = "NO_CANDIDATE"
	ErrorResponseErrorCodeNOTFOUND    ErrorResponseErrorCode = "NOT_FOUND"
)

// AllValues returns all ErrorResponseErrorCode values.
func (ErrorResponseErrorCode) AllValues() []ErrorResponseErrorCode {
	return []ErrorResponseErrorCode{
		ErrorResponseErrorCodeTEAMEXISTS,
		ErrorResponseErrorCodePREXISTS,
		ErrorResponseErrorCodePRMERGED,
		ErrorResponseErrorCodeNOTASSIGNED,
		ErrorResponseErrorCodeNOCANDIDATE,
		ErrorResponseErrorCodeNOTFOUND,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ErrorResponseErrorCode) MarshalText() ([]byte, error) {
	switch s {
	case ErrorResponseErrorCodeTEAMEXISTS:
		return []byte(s), nil
	case ErrorResponseErrorCodePREXISTS:
		return []byte(s), nil
	case ErrorResponseErrorCodePRMERGED:
		return []byte(s), nil
	case ErrorResponseErrorCodeNOTASSIGNED:
		return []byte(s), nil
	case ErrorResponseErrorCodeNOCANDIDATE:
		return []byte(s), nil
	case ErrorResponseErrorCodeNOTFOUND:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ErrorResponseErrorCode) UnmarshalText(data []byte) error {
	switch ErrorResponseErrorCode(data) {
	case ErrorResponseErrorCodeTEAMEXISTS:
		*s = ErrorResponseErrorCodeTEAMEXISTS
		return nil
	case ErrorResponseErrorCodePREXISTS:
		*s = ErrorResponseErrorCodePREXISTS
		return nil
	case ErrorResponseErrorCodePRMERGED:
		*s = ErrorResponseErrorCodePRMERGED
		return nil
	case ErrorResponseErrorCodeNOTASSIGNED:
		*s = ErrorResponseErrorCodeNOTASSIGNED
		return nil
	case ErrorResponseErrorCodeNOCANDIDATE:
		*s = ErrorResponseErrorCodeNOCANDIDATE
		return nil
	case ErrorResponseErrorCodeNOTFOUND:
		*s = ErrorResponseErrorCodeNOTFOUND
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPullRequest returns new OptPullRequest with value set to v.
func NewOptPullRequest(v PullRequest) OptPullRequest {
	return OptPullRequest{
		Value: v,
		Set:   true,
	}
}

// OptPullRequest is optional PullRequest.
type OptPullRequest struct {
	Value PullRequest
	Set   bool
}

// IsSet returns true if OptPullRequest was set.
func (o OptPullRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPullRequest) Reset() {
	var v PullRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPullRequest) SetTo(v PullRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPullRequest) Get() (v PullRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPullRequest) Or(d PullRequest) PullRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTeam returns new OptTeam with value set to v.
func NewOptTeam(v Team) OptTeam {
	return OptTeam{
		Value: v,
		Set:   true,
	}
}

// OptTeam is optional Team.
type OptTeam struct {
	Value Team
	Set   bool
}

// IsSet returns true if OptTeam was set.
func (o OptTeam) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTeam) Reset() {
	var v Team
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTeam) SetTo(v Team) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTeam) Get() (v Team, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTeam) Or(d Team) Team {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUser returns new OptUser with value set to v.
func NewOptUser(v User) OptUser {
	return OptUser{
		Value: v,
		Set:   true,
	}
}

// OptUser is optional User.
type OptUser struct {
	Value User
	Set   bool
}

// IsSet returns true if OptUser was set.
func (o OptUser) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUser) Reset() {
	var v User
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUser) SetTo(v User) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUser) Get() (v User, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUser) Or(d User) User {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PullRequest
type PullRequest struct {
	PullRequestID   string            `json:"pull_request_id"`
	PullRequestName string            `json:"pull_request_name"`
	AuthorID        string            `json:"author_id"`
	Status          PullRequestStatus `json:"status"`
	// User_id назначенных ревьюверов (0..2).
	AssignedReviewers []string       `json:"assigned_reviewers"`
	CreatedAt         OptNilDateTime `json:"createdAt"`
	MergedAt          OptNilDateTime `json:"mergedAt"`
}

// GetPullRequestID returns the value of PullRequestID.
func (s *PullRequest) GetPullRequestID() string {
	return s.PullRequestID
}

// GetPullRequestName returns the value of PullRequestName.
func (s *PullRequest) GetPullRequestName() string {
	return s.PullRequestName
}

// GetAuthorID returns the value of AuthorID.
func (s *PullRequest) GetAuthorID() string {
	return s.AuthorID
}

// GetStatus returns the value of Status.
func (s *PullRequest) GetStatus() PullRequestStatus {
	return s.Status
}

// GetAssignedReviewers returns the value of AssignedReviewers.
func (s *PullRequest) GetAssignedReviewers() []string {
	return s.AssignedReviewers
}

// GetCreatedAt returns the value of CreatedAt.
func (s *PullRequest) GetCreatedAt() OptNilDateTime {
	return s.CreatedAt
}

// GetMergedAt returns the value of MergedAt.
func (s *PullRequest) GetMergedAt() OptNilDateTime {
	return s.MergedAt
}

// SetPullRequestID sets the value of PullRequestID.
func (s *PullRequest) SetPullRequestID(val string) {
	s.PullRequestID = val
}

// SetPullRequestName sets the value of PullRequestName.
func (s *PullRequest) SetPullRequestName(val string) {
	s.PullRequestName = val
}

// SetAuthorID sets the value of AuthorID.
func (s *PullRequest) SetAuthorID(val string) {
	s.AuthorID = val
}

// SetStatus sets the value of Status.
func (s *PullRequest) SetStatus(val PullRequestStatus) {
	s.Status = val
}

// SetAssignedReviewers sets the value of AssignedReviewers.
func (s *PullRequest) SetAssignedReviewers(val []string) {
	s.AssignedReviewers = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *PullRequest) SetCreatedAt(val OptNilDateTime) {
	s.CreatedAt = val
}

// SetMergedAt sets the value of MergedAt.
func (s *PullRequest) SetMergedAt(val OptNilDateTime) {
	s.MergedAt = val
}

type PullRequestCreatePostConflict ErrorResponse

func (*PullRequestCreatePostConflict) pullRequestCreatePostRes() {}

type PullRequestCreatePostCreated struct {
	Pr OptPullRequest `json:"pr"`
}

// GetPr returns the value of Pr.
func (s *PullRequestCreatePostCreated) GetPr() OptPullRequest {
	return s.Pr
}

// SetPr sets the value of Pr.
func (s *PullRequestCreatePostCreated) SetPr(val OptPullRequest) {
	s.Pr = val
}

func (*PullRequestCreatePostCreated) pullRequestCreatePostRes() {}

type PullRequestCreatePostNotFound ErrorResponse

func (*PullRequestCreatePostNotFound) pullRequestCreatePostRes() {}

type PullRequestCreatePostReq struct {
	PullRequestID   string `json:"pull_request_id"`
	PullRequestName string `json:"pull_request_name"`
	AuthorID        string `json:"author_id"`
}

// GetPullRequestID returns the value of PullRequestID.
func (s *PullRequestCreatePostReq) GetPullRequestID() string {
	return s.PullRequestID
}

// GetPullRequestName returns the value of PullRequestName.
func (s *PullRequestCreatePostReq) GetPullRequestName() string {
	return s.PullRequestName
}

// GetAuthorID returns the value of AuthorID.
func (s *PullRequestCreatePostReq) GetAuthorID() string {
	return s.AuthorID
}

// SetPullRequestID sets the value of PullRequestID.
func (s *PullRequestCreatePostReq) SetPullRequestID(val string) {
	s.PullRequestID = val
}

// SetPullRequestName sets the value of PullRequestName.
func (s *PullRequestCreatePostReq) SetPullRequestName(val string) {
	s.PullRequestName = val
}

// SetAuthorID sets the value of AuthorID.
func (s *PullRequestCreatePostReq) SetAuthorID(val string) {
	s.AuthorID = val
}

type PullRequestMergePostOK struct {
	Pr OptPullRequest `json:"pr"`
}

// GetPr returns the value of Pr.
func (s *PullRequestMergePostOK) GetPr() OptPullRequest {
	return s.Pr
}

// SetPr sets the value of Pr.
func (s *PullRequestMergePostOK) SetPr(val OptPullRequest) {
	s.Pr = val
}

func (*PullRequestMergePostOK) pullRequestMergePostRes() {}

type PullRequestMergePostReq struct {
	PullRequestID string `json:"pull_request_id"`
}

// GetPullRequestID returns the value of PullRequestID.
func (s *PullRequestMergePostReq) GetPullRequestID() string {
	return s.PullRequestID
}

// SetPullRequestID sets the value of PullRequestID.
func (s *PullRequestMergePostReq) SetPullRequestID(val string) {
	s.PullRequestID = val
}

type PullRequestReassignPostConflict ErrorResponse

func (*PullRequestReassignPostConflict) pullRequestReassignPostRes() {}

type PullRequestReassignPostNotFound ErrorResponse

func (*PullRequestReassignPostNotFound) pullRequestReassignPostRes() {}

type PullRequestReassignPostOK struct {
	Pr PullRequest `json:"pr"`
	// User_id нового ревьювера.
	ReplacedBy string `json:"replaced_by"`
}

// GetPr returns the value of Pr.
func (s *PullRequestReassignPostOK) GetPr() PullRequest {
	return s.Pr
}

// GetReplacedBy returns the value of ReplacedBy.
func (s *PullRequestReassignPostOK) GetReplacedBy() string {
	return s.ReplacedBy
}

// SetPr sets the value of Pr.
func (s *PullRequestReassignPostOK) SetPr(val PullRequest) {
	s.Pr = val
}

// SetReplacedBy sets the value of ReplacedBy.
func (s *PullRequestReassignPostOK) SetReplacedBy(val string) {
	s.ReplacedBy = val
}

func (*PullRequestReassignPostOK) pullRequestReassignPostRes() {}

type PullRequestReassignPostReq struct {
	PullRequestID string `json:"pull_request_id"`
	OldUserID     string `json:"old_user_id"`
}

// GetPullRequestID returns the value of PullRequestID.
func (s *PullRequestReassignPostReq) GetPullRequestID() string {
	return s.PullRequestID
}

// GetOldUserID returns the value of OldUserID.
func (s *PullRequestReassignPostReq) GetOldUserID() string {
	return s.OldUserID
}

// SetPullRequestID sets the value of PullRequestID.
func (s *PullRequestReassignPostReq) SetPullRequestID(val string) {
	s.PullRequestID = val
}

// SetOldUserID sets the value of OldUserID.
func (s *PullRequestReassignPostReq) SetOldUserID(val string) {
	s.OldUserID = val
}

// Ref: #/components/schemas/PullRequestShort
type PullRequestShort struct {
	PullRequestID   string                 `json:"pull_request_id"`
	PullRequestName string                 `json:"pull_request_name"`
	AuthorID        string                 `json:"author_id"`
	Status          PullRequestShortStatus `json:"status"`
}

// GetPullRequestID returns the value of PullRequestID.
func (s *PullRequestShort) GetPullRequestID() string {
	return s.PullRequestID
}

// GetPullRequestName returns the value of PullRequestName.
func (s *PullRequestShort) GetPullRequestName() string {
	return s.PullRequestName
}

// GetAuthorID returns the value of AuthorID.
func (s *PullRequestShort) GetAuthorID() string {
	return s.AuthorID
}

// GetStatus returns the value of Status.
func (s *PullRequestShort) GetStatus() PullRequestShortStatus {
	return s.Status
}

// SetPullRequestID sets the value of PullRequestID.
func (s *PullRequestShort) SetPullRequestID(val string) {
	s.PullRequestID = val
}

// SetPullRequestName sets the value of PullRequestName.
func (s *PullRequestShort) SetPullRequestName(val string) {
	s.PullRequestName = val
}

// SetAuthorID sets the value of AuthorID.
func (s *PullRequestShort) SetAuthorID(val string) {
	s.AuthorID = val
}

// SetStatus sets the value of Status.
func (s *PullRequestShort) SetStatus(val PullRequestShortStatus) {
	s.Status = val
}

type PullRequestShortStatus string

const (
	PullRequestShortStatusOPEN   PullRequestShortStatus = "OPEN"
	PullRequestShortStatusMERGED PullRequestShortStatus = "MERGED"
)

// AllValues returns all PullRequestShortStatus values.
func (PullRequestShortStatus) AllValues() []PullRequestShortStatus {
	return []PullRequestShortStatus{
		PullRequestShortStatusOPEN,
		PullRequestShortStatusMERGED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PullRequestShortStatus) MarshalText() ([]byte, error) {
	switch s {
	case PullRequestShortStatusOPEN:
		return []byte(s), nil
	case PullRequestShortStatusMERGED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PullRequestShortStatus) UnmarshalText(data []byte) error {
	switch PullRequestShortStatus(data) {
	case PullRequestShortStatusOPEN:
		*s = PullRequestShortStatusOPEN
		return nil
	case PullRequestShortStatusMERGED:
		*s = PullRequestShortStatusMERGED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type PullRequestStatus string

const (
	PullRequestStatusOPEN   PullRequestStatus = "OPEN"
	PullRequestStatusMERGED PullRequestStatus = "MERGED"
)

// AllValues returns all PullRequestStatus values.
func (PullRequestStatus) AllValues() []PullRequestStatus {
	return []PullRequestStatus{
		PullRequestStatusOPEN,
		PullRequestStatusMERGED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PullRequestStatus) MarshalText() ([]byte, error) {
	switch s {
	case PullRequestStatusOPEN:
		return []byte(s), nil
	case PullRequestStatusMERGED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PullRequestStatus) UnmarshalText(data []byte) error {
	switch PullRequestStatus(data) {
	case PullRequestStatusOPEN:
		*s = PullRequestStatusOPEN
		return nil
	case PullRequestStatusMERGED:
		*s = PullRequestStatusMERGED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Team
type Team struct {
	TeamName string       `json:"team_name"`
	Members  []TeamMember `json:"members"`
}

// GetTeamName returns the value of TeamName.
func (s *Team) GetTeamName() string {
	return s.TeamName
}

// GetMembers returns the value of Members.
func (s *Team) GetMembers() []TeamMember {
	return s.Members
}

// SetTeamName sets the value of TeamName.
func (s *Team) SetTeamName(val string) {
	s.TeamName = val
}

// SetMembers sets the value of Members.
func (s *Team) SetMembers(val []TeamMember) {
	s.Members = val
}

func (*Team) teamGetGetRes() {}

type TeamAddPostCreated struct {
	Team OptTeam `json:"team"`
}

// GetTeam returns the value of Team.
func (s *TeamAddPostCreated) GetTeam() OptTeam {
	return s.Team
}

// SetTeam sets the value of Team.
func (s *TeamAddPostCreated) SetTeam(val OptTeam) {
	s.Team = val
}

func (*TeamAddPostCreated) teamAddPostRes() {}

// Ref: #/components/schemas/TeamMember
type TeamMember struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
	IsActive bool   `json:"is_active"`
}

// GetUserID returns the value of UserID.
func (s *TeamMember) GetUserID() string {
	return s.UserID
}

// GetUsername returns the value of Username.
func (s *TeamMember) GetUsername() string {
	return s.Username
}

// GetIsActive returns the value of IsActive.
func (s *TeamMember) GetIsActive() bool {
	return s.IsActive
}

// SetUserID sets the value of UserID.
func (s *TeamMember) SetUserID(val string) {
	s.UserID = val
}

// SetUsername sets the value of Username.
func (s *TeamMember) SetUsername(val string) {
	s.Username = val
}

// SetIsActive sets the value of IsActive.
func (s *TeamMember) SetIsActive(val bool) {
	s.IsActive = val
}

// Ref: #/components/schemas/User
type User struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
	TeamName string `json:"team_name"`
	IsActive bool   `json:"is_active"`
}

// GetUserID returns the value of UserID.
func (s *User) GetUserID() string {
	return s.UserID
}

// GetUsername returns the value of Username.
func (s *User) GetUsername() string {
	return s.Username
}

// GetTeamName returns the value of TeamName.
func (s *User) GetTeamName() string {
	return s.TeamName
}

// GetIsActive returns the value of IsActive.
func (s *User) GetIsActive() bool {
	return s.IsActive
}

// SetUserID sets the value of UserID.
func (s *User) SetUserID(val string) {
	s.UserID = val
}

// SetUsername sets the value of Username.
func (s *User) SetUsername(val string) {
	s.Username = val
}

// SetTeamName sets the value of TeamName.
func (s *User) SetTeamName(val string) {
	s.TeamName = val
}

// SetIsActive sets the value of IsActive.
func (s *User) SetIsActive(val bool) {
	s.IsActive = val
}

type UsersGetReviewGetOK struct {
	UserID       string             `json:"user_id"`
	PullRequests []PullRequestShort `json:"pull_requests"`
}

// GetUserID returns the value of UserID.
func (s *UsersGetReviewGetOK) GetUserID() string {
	return s.UserID
}

// GetPullRequests returns the value of PullRequests.
func (s *UsersGetReviewGetOK) GetPullRequests() []PullRequestShort {
	return s.PullRequests
}

// SetUserID sets the value of UserID.
func (s *UsersGetReviewGetOK) SetUserID(val string) {
	s.UserID = val
}

// SetPullRequests sets the value of PullRequests.
func (s *UsersGetReviewGetOK) SetPullRequests(val []PullRequestShort) {
	s.PullRequests = val
}

type UsersSetIsActivePostOK struct {
	User OptUser `json:"user"`
}

// GetUser returns the value of User.
func (s *UsersSetIsActivePostOK) GetUser() OptUser {
	return s.User
}

// SetUser sets the value of User.
func (s *UsersSetIsActivePostOK) SetUser(val OptUser) {
	s.User = val
}

func (*UsersSetIsActivePostOK) usersSetIsActivePostRes() {}

type UsersSetIsActivePostReq struct {
	UserID   string `json:"user_id"`
	IsActive bool   `json:"is_active"`
}

// GetUserID returns the value of UserID.
func (s *UsersSetIsActivePostReq) GetUserID() string {
	return s.UserID
}

// GetIsActive returns the value of IsActive.
func (s *UsersSetIsActivePostReq) GetIsActive() bool {
	return s.IsActive
}

// SetUserID sets the value of UserID.
func (s *UsersSetIsActivePostReq) SetUserID(val string) {
	s.UserID = val
}

// SetIsActive sets the value of IsActive.
func (s *UsersSetIsActivePostReq) SetIsActive(val bool) {
	s.IsActive = val
}
