// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

// TeamGetGetParams is parameters of GET /team/get operation.
type TeamGetGetParams struct {
	// Уникальное имя команды.
	TeamName string
}

func unpackTeamGetGetParams(packed middleware.Parameters) (params TeamGetGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "team_name",
			In:   "query",
		}
		params.TeamName = packed[key].(string)
	}
	return params
}

func decodeTeamGetGetParams(args [0]string, argsEscaped bool, r *http.Request) (params TeamGetGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: team_name.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "team_name",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.TeamName = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "team_name",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// UsersGetReviewGetParams is parameters of GET /users/getReview operation.
type UsersGetReviewGetParams struct {
	// Идентификатор пользователя.
	UserID string
}

func unpackUsersGetReviewGetParams(packed middleware.Parameters) (params UsersGetReviewGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "user_id",
			In:   "query",
		}
		params.UserID = packed[key].(string)
	}
	return params
}

func decodeUsersGetReviewGetParams(args [0]string, argsEscaped bool, r *http.Request) (params UsersGetReviewGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: user_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "user_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.UserID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "user_id",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
