// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// PullRequestCreatePost implements POST /pullRequest/create operation.
	//
	// Создать PR и автоматически назначить до 2 ревьюверов
	// из команды автора.
	//
	// POST /pullRequest/create
	PullRequestCreatePost(ctx context.Context, req *PullRequestCreatePostReq) (PullRequestCreatePostRes, error)
	// PullRequestMergePost implements POST /pullRequest/merge operation.
	//
	// Пометить PR как MERGED (идемпотентная операция).
	//
	// POST /pullRequest/merge
	PullRequestMergePost(ctx context.Context, req *PullRequestMergePostReq) (PullRequestMergePostRes, error)
	// PullRequestReassignPost implements POST /pullRequest/reassign operation.
	//
	// Переназначить конкретного ревьювера на другого из
	// его команды.
	//
	// POST /pullRequest/reassign
	PullRequestReassignPost(ctx context.Context, req *PullRequestReassignPostReq) (PullRequestReassignPostRes, error)
	// TeamAddPost implements POST /team/add operation.
	//
	// Создать команду с участниками (создаёт/обновляет
	// пользователей).
	//
	// POST /team/add
	TeamAddPost(ctx context.Context, req *Team) (TeamAddPostRes, error)
	// TeamGetGet implements GET /team/get operation.
	//
	// Получить команду с участниками.
	//
	// GET /team/get
	TeamGetGet(ctx context.Context, params TeamGetGetParams) (TeamGetGetRes, error)
	// UsersGetReviewGet implements GET /users/getReview operation.
	//
	// Получить PR'ы, где пользователь назначен ревьювером.
	//
	// GET /users/getReview
	UsersGetReviewGet(ctx context.Context, params UsersGetReviewGetParams) (*UsersGetReviewGetOK, error)
	// UsersSetIsActivePost implements POST /users/setIsActive operation.
	//
	// Установить флаг активности пользователя.
	//
	// POST /users/setIsActive
	UsersSetIsActivePost(ctx context.Context, req *UsersSetIsActivePostReq) (UsersSetIsActivePostRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
